
services:
  web:
    build: .
    image: new-printimpact-web
    environment: [ "PORT=3000" ]
    expose: [ "3000" ]
    restart: unless-stopped
  proxy:
    image: caddy:2-alpine
    container_name: new-printimpact-proxy
    ports: [ "80:80", "443:443" ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [ web ]
    restart: unless-stopped
volumes: { caddy_data: {}, caddy_config: {} }
